
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { customStorageAdapter } from './storage';

const SUPABASE_URL = "https://lnezqzefqfjxukobnhpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZXpxemVmcWZqeHVrb2JuaHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTY2NjMsImV4cCI6MjA3MzM3MjY2M30.2fcydGArqi6m25uASdxBx4wfR9wNcU9pNVtJ0pJ32K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorageAdapter,
    persistSession: true,
    autoRefreshToken: true,
  }
});
